variable "target_project_id" {
  description = "Project that owns the task BigQuery dataset and task GSA"
  type        = string
}

variable "task_id" {
  description = "Approved data model task ID"
  type        = string
}

variable "task_name" {
  description = "Approved data model task name"
  type        = string
}

variable "group" {
  description = "Task group/domain code"
  type        = string
  default     = "analysis"
}

variable "request_user" {
  description = "Existing corporate user email. Identity lifecycle stays in Cloud Identity/Workspace/IdP."
  type        = string
  default     = ""
}

variable "dataset_id" {
  description = "BigQuery dataset ID generated by the Cloud Run adapter"
  type        = string
}

variable "bq_location" {
  description = "BigQuery dataset location"
  type        = string
  default     = "asia-northeast3"
}

variable "bigquery_role" {
  description = "Dataset access for request_user"
  type        = string
  default     = "editor"

  validation {
    condition     = contains(["viewer", "editor", "owner"], lower(var.bigquery_role))
    error_message = "bigquery_role must be viewer, editor, or owner."
  }
}

variable "gke_project_id" {
  description = "Project that owns the shared GKE cluster; empty means target_project_id"
  type        = string
  default     = ""
}

variable "gke_cluster_name" {
  description = "Shared GKE Autopilot cluster"
  type        = string
  default     = "analysis-autopilot-a"
}

variable "gke_location" {
  description = "Region of the shared GKE cluster"
  type        = string
  default     = "asia-northeast3"
}

variable "quota_cpu_requests" {
  type    = string
  default = "8"
}

variable "quota_cpu_limits" {
  type    = string
  default = "16"
}

variable "quota_memory_requests" {
  type    = string
  default = "32Gi"
}

variable "quota_memory_limits" {
  type    = string
  default = "64Gi"
}

variable "quota_pods" {
  type    = string
  default = "20"
}

variable "jupyter_image" {
  description = "Jupyter image. Pin a tag/digest in production."
  type        = string
  default     = "quay.io/jupyter/base-notebook:latest"
}

variable "jupyter_cpu_request" {
  type    = string
  default = "2"
}

variable "jupyter_cpu_limit" {
  type    = string
  default = "4"
}

variable "jupyter_memory_request" {
  type    = string
  default = "8Gi"
}

variable "jupyter_memory_limit" {
  type    = string
  default = "16Gi"
}

variable "storage_size" {
  description = "Jupyter workspace PVC size"
  type        = string
  default     = "50Gi"
}

variable "storage_class_name" {
  description = "Kubernetes StorageClass; empty uses the cluster default"
  type        = string
  default     = ""
}

variable "jupyter_service_type" {
  description = "ClusterIP is recommended; LoadBalancer can add cost/exposure"
  type        = string
  default     = "ClusterIP"

  validation {
    condition     = contains(["ClusterIP", "LoadBalancer"], var.jupyter_service_type)
    error_message = "jupyter_service_type must be ClusterIP or LoadBalancer."
  }
}

variable "expire_date" {
  description = "Business metadata for task lifecycle, YYYY-MM-DD"
  type        = string
  default     = ""
}
